/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { EtherSender, EtherSenderInterface } from "../EtherSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    name: "WithdrawalAmountExceedsBalance",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EtherSent",
    type: "event",
  },
  {
    inputs: [],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferEther",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101858061001f6000396000f3fe6080604052600436106100295760003560e01c806305b1137b1461002e578063722713f714610043575b600080fd5b61004161003c366004610117565b610064565b005b34801561004f57600080fd5b50333160405190815260200160405180910390f35b33318181101561009b576040516315e5cd3f60e31b8152336004820152602481018390526044810182905260640160405180910390fd5b6040516001600160a01b0384169083156108fc029084906000818181858888f193505050501580156100d1573d6000803e3d6000fd5b506040518281526001600160a01b0384169033907f10d1a5dc650a65cd6625a330078a13ee62c6ec85b36e94bdf57e4d3188ca67389060200160405180910390a3505050565b6000806040838503121561012a57600080fd5b82356001600160a01b038116811461014157600080fd5b94602093909301359350505056fea26469706673582212203f1473621b042079ba15416592620c5c2812d9ed67c1dd0e9554b3507131ff5864736f6c634300081b0033";

type EtherSenderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EtherSenderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EtherSender__factory extends ContractFactory {
  constructor(...args: EtherSenderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EtherSender & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EtherSender__factory {
    return super.connect(runner) as EtherSender__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EtherSenderInterface {
    return new Interface(_abi) as EtherSenderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): EtherSender {
    return new Contract(address, _abi, runner) as unknown as EtherSender;
  }
}
